[package]
name = "dyadikos-math"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
serde = { version = "1.0.143", features = ["derive"], optional = true }
bytemuck = { version = "1.11.0", features = ["derive"] }
nalgebra = "0.31.1"

[features]
serialize = ["serde"]
