[package]
name = "dyadikos-math"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
glam = "0.24.0"
serde = { version = "1.0.164", features = ["derive"], optional = true }
bytemuck = { version = "1.13.1", features = ["derive"] }

[features]
serialize = ["serde"]
