[package]
name = "dyadikos-math"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
glam = "0.21.3"
serde = { version = "1.0.143", features = ["derive"], optional = true }
bytemuck = { version = "1.11.0", features = ["derive"] }

[features]
serialize = ["serde"]
